name = "postgresql backup" # optional. if not set, the filename will be used without the extension

repositories = [
    "/tmp/restic-repo1",
    "s3:s3.amazonaws.com/bucket_name"
    ]

[execution]
parallel = true
retry_count = 10
retry_backoff = "1:00 exponential"  # 00:00 = min:sec; 00:00:00 = hour:min:sec
# strategies:
#  - static (same duration every try)
#  - linear (duration * retry number)
#  - exponential

[environment]
RESTIC_PASSWORD = "CHANGEME"
# or RESTIC_PASSWORD_FILE
# https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables

[backup]
sources = [
    "/var/lib/postgresql",
    "/etc/postgresql",
    "/tmp/pgdump.sql"
    ]

exclude_patterns = ['pg_stats_tmp/']
# exclude_files = []
# exclude_if_present = []

pre_hooks = ["systemctl stop postgresql"]
post_hooks = ["systemctl start postgresql"]

[prune]
keep-last =  3
keep-hourly =  5
keep-weekly = 10
keep-monthly = 30
group-by = "host,paths"
# https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy

[check]
checks = ["check-unused", "read-data"]


[metrics.prometheus]
path = "/var/lib/node_exporter/textfile_collector/runrestic.prom"
